import {
  type User,
  type NewUser,
  type UpdatedUser,
  type EmailOptions,
  type CookieOptions,
  type NewPost,
  type Post,
  type ResponsePosts,
  type ResponsePost,
  type NewReply,
  type Reply,
  type ResponseReplies,
  type UserFollows,
  type UserSearch,
} from "./types/types";
import { CustomError } from "./error/CustomError";
import { handleError } from "./error/errorHandler";
import {
  comparePassword,
  hashPassword,
  generateJWToken,
  generateVerificationToken,
  generateHashedToken,
} from "./encryption/encryption";
import {
  getUsersFromDb,
  getUserFromDb,
  checkUserWithEmail,
  addUserToDb,
  updateUserInDb,
  updateUserLimits,
  deleteUserFromDb,
  verifyUserInDb,
  addPostToDb,
  deletePostInDb,
  checkPostInDb,
  checkPostsInDb,
  getPostsFromDb,
  getPostFromDb,
  getUserPostsFromDb,
  getUserLikedPostsFromDb,
  updatePostLikesInDb,
  addReplyToDb,
  getPostRepliesFromDb,
  getReplyFromDb,
  updateReplyLikesInDb,
  deleteReplyInDb,
  getUserFollowsCountFromDb,
  getUserFollowsFromDb,
  updateUserFollowsInDb,
  getUsersSearchedFromDb,
} from "./db/query";
import { sendEmail } from "./email/email";
import cloudinaryConfig from "./config/cloudinary.config";
import { signUploadForm, deleteMedia } from "./modules/cloudinary.upload";

export {
  type User,
  type NewUser,
  type UpdatedUser,
  type EmailOptions,
  type CookieOptions,
  type NewPost,
  type Post,
  type ResponsePosts,
  type ResponsePost,
  type NewReply,
  type Reply,
  type ResponseReplies,
  type UserFollows,
  type UserSearch,
  CustomError,
  handleError,
  comparePassword,
  hashPassword,
  generateJWToken,
  generateVerificationToken,
  generateHashedToken,
  sendEmail,
  getUsersFromDb,
  getUserFromDb,
  checkUserWithEmail,
  addUserToDb,
  updateUserInDb,
  updateUserLimits,
  deleteUserFromDb,
  verifyUserInDb,
  cloudinaryConfig,
  signUploadForm,
  deleteMedia,
  addPostToDb,
  deletePostInDb,
  checkPostInDb,
  checkPostsInDb,
  getPostsFromDb,
  getPostFromDb,
  getUserPostsFromDb,
  getUserLikedPostsFromDb,
  updatePostLikesInDb,
  addReplyToDb,
  getPostRepliesFromDb,
  getReplyFromDb,
  updateReplyLikesInDb,
  deleteReplyInDb,
  getUserFollowsCountFromDb,
  getUserFollowsFromDb,
  updateUserFollowsInDb,
  getUsersSearchedFromDb,
};
